import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";

const Overlay = dynamic(() => import("../components/overlay"), { ssr: false });

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bronchy Overlay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Overlay />
      </main>
    </div>
  );
};

export default Home;
